doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            ocs:
                schema_filter: ~^.*$~
                url: '%env(resolve:OCS_DATABASE_URL)%'
        default_connection: 'default'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        # profiling_collect_backtrace: '%kernel.debug%'
        # use_savepoints: true
    orm:
        default_entity_manager: 'default'
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        entity_managers:
            # Important: Don't change order 'ocs' must go first to avoid problems with migrations
            ocs:
                connection: 'ocs'
                mappings:
                    ocs:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Ocs'
                        prefix: 'App\Entity\Ocs'
                        alias: Ocs
            default:
                connection: 'default'
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Default'
                        # If we put App\Entity\Default to prefix as it should, we get an error with php bin/console make:migration saying:
                        # "The class 'App\Entity\Ocs\Device' was not found in the chain configured namespaces App\Entity\Default"
                        # So we leave prefix as 'App\Entity' that works as spected
                        prefix: 'App\Entity'
                        alias: App
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
                # auto_mapping: true
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
